// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ProjectService.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251126210226_UpdateTemplateFeaturesToCollection")]
    partial class UpdateTemplateFeaturesToCollection
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DetailsConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RecommendedFor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DetailsConfigs");
                });

            modelBuilder.Entity("ProjectCreationWizardTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetailsConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ProjectCreationWizardTemplateCategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DetailsConfigId")
                        .IsUnique();

                    b.HasIndex("ProjectCreationWizardTemplateCategoryId");

                    b.ToTable("Templates");
                });

            modelBuilder.Entity("ProjectCreationWizardTemplateCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TemplateFeature", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("DetailsConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("IconKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DetailsConfigId");

                    b.ToTable("TemplateFeatures");
                });

            modelBuilder.Entity("WorkTypeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("DetailsConfigId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DetailsConfigId");

                    b.ToTable("WorkTypes");
                });

            modelBuilder.Entity("ProjectCreationWizardTemplate", b =>
                {
                    b.HasOne("DetailsConfig", "DetailsConfig")
                        .WithOne()
                        .HasForeignKey("ProjectCreationWizardTemplate", "DetailsConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProjectCreationWizardTemplateCategory", "Category")
                        .WithMany("ProjectTemplates")
                        .HasForeignKey("ProjectCreationWizardTemplateCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CardConfig", "CardConfig", b1 =>
                        {
                            b1.Property<Guid>("ProjectCreationWizardTemplateId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("IconKey")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("IconName")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("ProjectCreationWizardTemplateId");

                            b1.ToTable("Templates");

                            b1.WithOwner()
                                .HasForeignKey("ProjectCreationWizardTemplateId");
                        });

                    b.Navigation("CardConfig")
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("DetailsConfig");
                });

            modelBuilder.Entity("TemplateFeature", b =>
                {
                    b.HasOne("DetailsConfig", "DetailsConfig")
                        .WithMany("TemplateFeatures")
                        .HasForeignKey("DetailsConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailsConfig");
                });

            modelBuilder.Entity("WorkTypeItem", b =>
                {
                    b.HasOne("DetailsConfig", "DetailsConfig")
                        .WithMany("WorkTypes")
                        .HasForeignKey("DetailsConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DetailsConfig");
                });

            modelBuilder.Entity("DetailsConfig", b =>
                {
                    b.Navigation("TemplateFeatures");

                    b.Navigation("WorkTypes");
                });

            modelBuilder.Entity("ProjectCreationWizardTemplateCategory", b =>
                {
                    b.Navigation("ProjectTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
